### PR TITLE
Add step for updating Julia packages by Jules-Bertholet

### PR DESCRIPTION
**Pull request by s34m**
[Source](https://github.com/r-darwish/topgrade/pull/1009#issue-1376941751l)

### CODE REVIEW

**Comment by kunzaatko** [comment]
Hi! Are you planning to merge it into the successor repository of topgrade, to topgrade-rs?

**Comment by s34m** [comment]
It should be already in the main repo

**Comment by kunzaatko** [comment]
Oh, OK then. I didn't find the relevant PR. Sorry then.

**Comment by s34m** [comment]
No problem and thanks for remembering it. If you find any things missing in upstream, please just open an issue there, thank you for your help :)

**Pull request merged**
